cd %APPDATA%\.minecraft\
(
	echo ofFogType:3
	echo ofFogStart:0.6
	echo ofMipmapType:0
	echo ofOcclusionFancy:false
	echo ofSmoothFps:false
	echo ofSmoothWorld:false
	echo ofAoLevel:0.0
	echo ofClouds:3
	echo ofCloudsHeight:0.0
	echo ofTrees:1
	echo ofDroppedItems:1
	echo ofRain:3
	echo ofAnimatedWater:0
	echo ofAnimatedLava:0
	echo ofAnimatedFire:true
	echo ofAnimatedPortal:true
	echo ofAnimatedRedstone:false
	echo ofAnimatedExplosion:true
	echo ofAnimatedFlame:true
	echo ofAnimatedSmoke:true
	echo ofVoidParticles:false
	echo ofWaterParticles:true
	echo ofPortalParticles:true
	echo ofPotionParticles:true
	echo ofFireworkParticles:true
	echo ofDrippingWaterLava:true
	echo ofAnimatedTerrain:true
	echo ofAnimatedTextures:true
	echo ofRainSplash:false
	echo ofLagometer:false
	echo ofShowFps:false
	echo ofAutoSaveTicks:28800
	echo ofBetterGrass:3
	echo ofConnectedTextures:3
	echo ofWeather:false
	echo ofSky:false
	echo ofStars:false
	echo ofSunMoon:true
	echo ofVignette:1
	echo ofChunkUpdates:1
	echo ofChunkUpdatesDynamic:false
	echo ofTime:0
	echo ofClearWater:false
	echo ofAaLevel:0
	echo ofAfLevel:1
	echo ofProfiler:false
	echo ofBetterSnow:false
	echo ofSwampColors:false
	echo ofRandomEntities:false
	echo ofSmoothBiomes:false
	echo ofCustomFonts:false
	echo ofCustomColors:false
	echo ofCustomItems:false
	echo ofCustomSky:true
	echo ofShowCapes:true
	echo ofNaturalTextures:false
	echo ofEmissiveTextures:false
	echo ofLazyChunkLoading:true
	echo ofRenderRegions:true
	echo ofSmartAnimations:true
	echo ofDynamicFov:true
	echo ofAlternateBlocks:false
	echo ofDynamicLights:3
	echo ofScreenshotSize:1
	echo ofCustomEntityModels:false
	echo ofCustomGuis:false
	echo ofShowGlErrors:false
	echo ofFullscreenMode:Default
	echo ofFastMath:true
	echo ofFastRender:true
	echo ofTranslucentBlocks:1
	echo key_of.key.zoom:29
) > optionsof.txt